### ISSUE TITLE
Move metadata to post files

### ISSUE THREAD

**Issue by jmglov** [borkdude/quickblog#13]
Keeping the post metadata in `posts.edn` requires you to make changes in two places when adding a new post, and also makes caching slightly more complex. As MultiMarkdown (the markdown flavour implemented by markdown-clj) has support for [including metadata at the beginning of a file](https://github.com/fletcher/MultiMarkdown/wiki/MultiMarkdown-Syntax-Guide#metadata), we can move the metadata to the posts files themselves and not require `posts.edn` anymore.

**Comment by borkdude** [comment]
I'm all for doing this and in fact, I did try to make this work before moving my blog to this library, but it had a couple of downsizes. The primary downside being having to read through all files when refreshing the index/archive/tags pages, but with the right caching in place, this should also be solveable.

**Comment by borkdude** [comment]
So, PR welcome! Note that I'd like first see #12 to be solved since that's a regression.

**Comment by jmglov** [comment]
@borkdude This can be closed now.
