### ISSUE TITLE
Regression: planetclojure.xml feed is empty

### ISSUE THREAD

**Issue by borkdude** [borkdude/quickblog#18]
See https://blog.michielborkent.nl/planetclojure.xml

cc @jmglov

**Comment by borkdude** [comment]
Fixed.

**Comment by borkdude** [comment]
It works again :-)

<img width="653" alt="Screenshot 2022-08-02 at 13 41 42" src="https://user-images.githubusercontent.com/284934/182366319-132c2210-9f03-4efa-b2aa-c369ca155ad8.png">

**Comment by jmglov** [comment]
Ugh, sorry about that. As soon as I finish this caching PR, I'll create a branch to add some tests.
