### ISSUE TITLE
No social media preview on Twitter?

### ISSUE THREAD

**Issue by borkdude** [borkdude/quickblog#44]
I posted the https://blog.michielborkent.nl/babashka-test-runner.html  link to Twitter, but no social media preview appeared.

cc @jmglov

**Comment by jmglov** [comment]
There are a few problems here:
- Your [base template](https://github.com/borkdude/blog/blob/main/templates/base.html) doesn't contain the social sharing meta tags. Compare to the latest [base template](https://github.com/borkdude/quickblog/blob/main/resources/quickblog/templates/base.html#L15) from quickblog. You can fix this by running `bb quickblog refresh-templates` in your blog repo.
- Your post's [Markdown file](https://raw.githubusercontent.com/borkdude/blog/main/posts/babashka-test-runner.md) doesn't contain a `Description` or `Image` metadata line. You can add something like this:
  ``` text
  Title: Sharing is caring
  Date: 2022-08-16
  Tags: demo
  Image: assets/2022-08-16-sharing-preview.png
  Image-Alt: A leather-bound notebook lies open on a writing desk
  Twitter-Handle: quickblog
  Description: quickblog now creates nifty social media sharing cards / previews. Read all about how this works and how you can maximise engagement with your posts!
  
  You may have already heard the good news: quickblog is more social than ever!
  ...
  ```

I'll try to make this more obvious in the documentation.

**Comment by borkdude** [comment]
Thanks! I'll try this next time I write a blog
