### ISSUE TITLE
Cannot create a blog post without tags

### ISSUE THREAD

**Issue by formsandlines** [borkdude/quickblog#50]
When I try to create a new blog post using the example mentioned in the “Quickstart” section of the README `bb quickblog new --file "test.md" --title "Test"`, I get an error `Missing required argument --tags`. When I just add `--tags` without an argument, it automatically creates a tag `true` which is added to my blog post.

I used quickblog with the SHA of the latest commit, which is [`d17149f9dc5ed6ec2d366759f4190ec78f6ca337`](https://github.com/borkdude/quickblog/commit/d17149f9dc5ed6ec2d366759f4190ec78f6ca337).

**Comment by borkdude** [comment]
Should work now
