### ISSUE TITLE
Default tag `clojure` added automatically without ability to change or have no tags at all

### ISSUE THREAD

**Issue by formsandlines** [borkdude/quickblog#51]
In the latest commit, while the `--tags` option for `quickblog new` is not required anymore, the default tag `clojure` is still added automatically. I would prefer to be able to specify a different default tag or none at all, if desired.

@borkdude suggested introducing a `:default-tags` option, which I think is a good idea. I guess setting this to an empty vector could get rid of the `Tags: …` field in .md files entirely or just leave it empty.

**Comment by borkdude** [comment]
Sounds good. cc @jmglov

**Comment by formsandlines** [comment]
I just made a PR on this issue (actually my first-ever, so I hope everything is fine :)): https://github.com/borkdude/quickblog/pull/52

“Tagged:” will still appear in the HTML output, maybe it could be removed if there are no tags, but I wasn’t sure how to check for an empty collection in the template language (`{% if tags %}` didn’t seem to work).

**Comment by borkdude** [comment]
@formsandlines I added a test runner on CI now. I noticed there were some flaky tests and I disabled those. Can you merge the main branch into your PR so your PR will run the tests automatically as well? Then I'll look at the rest of your PR.

**Comment by borkdude** [comment]
Updated the PR via the Github UI
